### ISSUE TITLE
Eigenes Anmeldeformular einfügen

### ISSUE THREAD

**Issue by schaffen** [markocupic/calendar-event-booking-bundle#1]
Hallo,

ich hätte eine Frage bzgl. der Integration eines eigenen Anmeldeformulars. 
Im Backend wäre ja unter dem Abschnitt "Anmeldung über ein Formular" ein Anmeldeformular auszuwählen. Mit dem Hinweis: Das gewählte Anmeldeformular wird im angepassten Event Template eingefügt.

Leider bekomme ich es nicht hin, ein eigenes Form. zu integrieren. Bzw. wird das ausgewählte Form. nicht angezeigt.

Bitte um Ihre geschätzte Info. Vielen Dank!

LG

**Comment by markocupic** [comment]
Hallo schaffen
Die neuste Version war noch nicht getagt. Sorry. 
Lade dir die Version 0.0.15 runter. Cache leeren & Installtool laufen lassen. 
Danach erscheint in den Moduleinstellungen die Formularauswahl. 

Liebe Grüsse und viel Spass mit der Erweiterung
Marko
