### ISSUE TITLE
Begleitpersonen für maximale Teilnehmeranzahl berücksichtigen

### ISSUE THREAD

**Issue by DanEi75** [markocupic/calendar-event-booking-bundle#10]
Hi @markocupic 

Diese Erweiterung ist für meinen Anwendungsfall fast perfekt!

Nur eines ist mir aufgefallen: Bei der maximalen Teilnehmeranzahl werden die Begleitpersonen nicht berücksichtigt, oder? Also, im Extremfall, kann z.B. die max. Teilnehmeranzahl 10 sein, und zehn Anmeldungen mit z.B. je zwei Begleitpersonen wären möglich, oder? Zumindest konnte ich es machen.

Für meinen Anwendungsfall sollten die Begleitpersonen für die maximale Teilnehmeranzahl auch berücksichtigt werden. Irgendeine Chance, dies umzusetzen?

Danke dir für die Rückmeldung!

**Comment by markocupic** [comment]
Hallo DanEi75

Das Modul habe ich damals für einen Kunden erstellt. Dieser wollte das eben nicht so.

Ich könnte dir das schon anpassen, aber würde dafür etwas Entschädigung verlangen.

Sorry, ich muss mich da etwas abgrenzen. Anfragen wie diese kommen bei 90 Erweiterungen auf github fast täglich.

Liebe Grüsse

 

Marko
 

--------------------------------------
Marko Cupic
Surenweidstr. 2
CH-6208 Oberkirch

http://4ae-racing-team.ch
http://kletterkader.com

 
 

Gesendet: Dienstag, 05. Februar 2019 um 17:38 Uhr
Von: "DanEi75" <notifications@github.com>
An: markocupic/calendar-event-booking-bundle <calendar-event-booking-bundle@noreply.github.com>
Cc: "Marko Cupic" <m.cupic@gmx.ch>, Mention <mention@noreply.github.com>
Betreff: [markocupic/calendar-event-booking-bundle] Begleitpersonen für maximale Teilnehmeranzahl berücksichtigen (#10)


Hi @markocupic

Diese Erweiterung ist für meinen Anwendungsfall fast perfekt!

Nur eines ist mir aufgefallen: Bei der maximalen Teilnehmeranzahl werden die Begleitpersonen nicht berücksichtigt, oder? Also, im Extremfall, kann z.B. die max. Teilnehmeranzahl 10 sein, und zehn Anmeldungen mit z.B. je zwei Begleitpersonen wären möglich, oder? Zumindest konnte ich es machen.

Für meinen Anwendungsfall sollten die Begleitpersonen für die maximale Teilnehmeranzahl auch berücksichtigt werden. Irgendeine Chance, dies umzusetzen?

Danke dir für die Rückmeldung!

**Comment by DanEi75** [comment]
Hallo @markocupic 

Kein Thema! Ich versteh dich völlig und Arbeit soll vergütet werden ;-)!

Ich habe mir den Quellcode etwas angeschaut und ich meine, das lässt sich prima als Option umsetzen. Ich möchte zuerst noch etwas selber basteln und komme dann gerne auf dich zu. Eventuell nehme ich dir etwas Arbeit ab, damit du es in den Core einbauen kannst, wenn du möchtest.

LG

**Comment by markocupic** [comment]
Alles klar. Nur zu. Am besten als Option in tl_calendar_events.
LG Marko

**Comment by DanEi75** [comment]
Hallo Marko

So, bin erst gestern dazu gekommen. Ich habe das mal wie folgt eingebaut und getestet. Ich meine, das klappt ziemlich gut und korrekt. Je nach Optionswahl wird die Teilnehmeranzahl in der Liste verändert und bei der FE-Buchung berücksichtigt. Aber ich bin jetzt definitiv nicht der Profi-Entwickler, deshalb auf eigene Gefahr, wenn du es in den Core einbetten möchtest ;-).

Ich hab das auf Github jetzt noch nie so dokumentiert und ich möchte jetzt auch nicht einen riesen Kommentar generieren. Hoffe, es passt, wenn ich dir die angepassten Dateien als zip-Datei einfüge.

[countEscorts.zip](https://github.com/markocupic/calendar-event-booking-bundle/files/2897752/countEscorts.zip)

**Hier für jede Datei noch die Anpassungen:**
- \src\Resources\contao\classes\dca\tl_calendar_events.php (Zeile 72-84)
- \src\Resources\contao\classes\hooks\ValidateForms.php (Zeile 165-187)
- \src\Resources\contao\dca\tl_calendar_events.php (Zeile 39-40 und 55-62)
- \src\Resources\contao\languages\de\default.php (Zeile 17) 
- \src\Resources\contao\languages\de\tl_calendar_events.php (Zeile 16)
- \src\Resources\contao\languages\en\default.php (Zeile 17) --> hab es auch nicht übersetzt ;-)
- \src\Resources\contao\languages\en\tl_calendar_events.php (Zeile 16) --> hab es auch nicht übersetzt ;-)
- \src\Resources\contao\modules\ModuleEventBooking.php (Zeile 142-155)

LG
Dani
