### ISSUE TITLE
Simple tokens ##member_salutation## und ##member_dateOfBirth## leer

### ISSUE THREAD

**Issue by pgerundt** [markocupic/calendar-event-booking-bundle#11]
Tolle Erweiterung, aber ich hab mich gewundert, warum die beiden Tokens ##member_salutation## und ##member_dateOfBirth## immer leer sind.

In https://github.com/markocupic/calendar-event-booking-bundle/blob/bc4aba5716f6e6edd2007de5e5574ad5d963cb23/src/Resources/contao/classes/hooks/ValidateForms.php#L271 dann die Lösung:
Sollte wohl korrekt `$arrTokens['member_salutation']` heißen.

Und Zeile
https://github.com/markocupic/calendar-event-booking-bundle/blob/bc4aba5716f6e6edd2007de5e5574ad5d963cb23/src/Resources/contao/classes/hooks/ValidateForms.php#L272
kann komplett gelöscht werden, denn `$objEventMember->dateOfBirth` ist kein Timestamp sondern das Geburtsdatum als String. `Date::parse()` gibt davon einen leeren String zurück.

Aber ansonsten: Daumen hoch!

**Comment by markocupic** [comment]
@pgerundt 
Besten Dank für den report:

> dann die Lösung: Sollte wohl korrekt $arrTokens['member_salutation'] heißen.
In Version 3.1 gefixt.

> Und Zeile 272 kann komplett gelöscht werden, denn $objEventMember->dateOfBirth ist kein Timestamp sondern das Geburtsdatum als String. Date::parse() gibt davon einen leeren String zurück.

Ab Version wandelt ein Hook den Datumsstring beim Absenden des Buchungsformulars in einen timestamp.
