### ISSUE TITLE
Export as Excel file and not only CSV

### ISSUE THREAD

**Issue by modir** [markocupic/calendar-event-booking-bundle#14]
We have some normal users where often have to explain again how to use CSV files and save them as Excel files after making some changes. It would be a lot easier for us if this bundle would have an Excel export as well. We use in our applications always this library: https://github.com/PHPOffice/PhpSpreadsheet

**Comment by markocupic** [comment]
Ciao Raffael
Du kannst mich gerne per Email kontaktieren. Ich würde dann die Anpassung im Rahmen eines Kleinauftrages für euch machen.
https://github.com/markocupic/calendar-event-booking-bundle/blob/514a76aa70d66464a5182f16e4c00b159b2c9b64/src/Resources/contao/config/config.php#L5

Liebe Grüsse
Marko
