### ISSUE TITLE
Maximale Teilnehmerzahl unwirksam

### ISSUE THREAD

**Issue by MartinFFM** [markocupic/calendar-event-booking-bundle#15]
Contao 4.9.2
calendar-event-booking-bundle 3.6.1

Danke für das Paket, das wird uns wahrscheinlich helfen, Anmeldungen im Charity-Bereich zu organisieren. Allerdings gibt es ein Problem:
Ich lege ein Event an, setze die maximale Teilnehmerzahl auf 2, testweise erst mal keine "Gäste am Rockzipfel" und danach kann ich so viele Teilnehmer anmelden, wie ich mag. Die erscheinen auch alle in der Teilnehmerliste des Events.

Da ich bei diesem Paket unerfahren bin: Ich weiß nicht, ob der Bug im Paket oder in meinem Kopf stattfindet ... Aber nach einigen Stunden mag ich ihn doch hier absetzen.

Danke schon jetzt fürs Kümmern!

**Comment by markocupic** [comment]
Komisch... Ich kann den Fehler nicht reproduzieren. Wie sehen denn die Eventeinstellungen aus?

**Comment by MartinFFM** [comment]
Eben angelegt:
Titel: Testtermin für 2 Personen
Startdatum: 09.05.2020
Enddatum: 09.05.2020
Veranstaltungsort, Strasse, PLZ, Ort sinnfrei bestückt
Haken bei Buchungsoptionen öffnen
Maximale Teilnehmerzahl: 2
Begleitpersonen: 0
Buchungen möglich ab: 05.05.2020
Buchungen möglich bis: 06.05.2020
Haken bei Mehrfachbuchung
Event veröffentlichen 2020-05-05 10:00 bis 2020-05-06 10:00

Es gibt die Seite "Auswahl" mit einem Modul EVENTLISTE, dort klickt man auf das Event. Für Events ist die Seite "Anmeldung" als Weiterleitungsseite benannt. Diese öffnet sich mit Klick auf das Event und enthält ein Modul EVENTLESER und ein Modul FORMULAR, in dem die Angaben zu machen sind; für das Fomular ist die "Aktiviere Event-Buchungsformular-Funktion" aktiviert.  Die Möglichkeit zur Abmeldung gibt es nicht, daher verweist die Abmeldeseite auf die Startseite.
Sind die Angaben im Formular gemacht, wird auf eine Seite "Rückmeldung zur Anmeldung" weiter geleitet. Dort kommt man immer an und der Datensatz wird immer der Liste hinzugefügt, egal wieviele Anmeldungen es schon gab.

Das "Drumherum" nur zur Einschätzung dessen, was ich gemacht habe. Wie geschrieben, Contao und dein Modul finde ich klasse, bin aber nicht sonderlich erfahren.

**Comment by markocupic** [comment]
Du kannst weiterhin Teilnehmer im Backend erfassen, auch wenn die Limite erreicht wurde?

Aber über das Frontendformular geht das nicht mehr. Oder? So ist es jedenfalls bei mir.

**Comment by markocupic** [comment]
Email: SMTP Einstellungen hast du gemacht in parameters.yml
Hat nichts mit meiner Erweiterung zu tun.

**Comment by MartinFFM** [comment]
> Aber über das Frontendformular geht das nicht mehr. Oder? So ist es jedenfalls bei mir.
Doch, das geht leider auch noch
