### ISSUE TITLE
Install Tool läuft nach Paketinstallation nicht

### ISSUE THREAD

**Issue by thomashinze** [markocupic/calendar-event-booking-bundle#16]
Contao 4.9.2 / Bundle 3.6.1 / PHP 7.3.11
Sobald ich das Bundle über den CM installiert habe muss ich die Datenbank aktualisieren.
Passwort InstallTool kann ich noch eingeben, danach weiße Seite. 
Im Backend sehe ich bereits Notification Center etc. aber der Aufruf klappt nicht. Tabellen sind ja nicht da / nicht aktuell.
Wenn ich die Bundle Erweiterung wieder entferne geht auch Install Tool wieder. 
Außer diesem Paket sind nur die CORE Pakete (News, Kalender, FAQ etc.) installiert

**Comment by markocupic** [comment]
irgend etwas im Log?

**Comment by markocupic** [comment]
Kann das jemand reproduzieren?

**Comment by thomashinze** [comment]
Hallo, Log ist leer. Es scheint ein Contao Problem zu sein. 
https://github.com/contao/contao/issues/962
Ich habe den RAM bei All Inkl. auf 1024MB erhöht und Install Tool lief durch.
Das Problem trat bei Paketen ohne Abhängigkeiten nicht auf. 
Da ich explizit das Booking Bundle wollte dachte ich es liegt am Paket.
