### ISSUE TITLE
Teilnehmer Export exportiert die ganze tl_calendar_events_member Tabelle

### ISSUE THREAD

**Issue by wiphi** [markocupic/calendar-event-booking-bundle#17]
Inder aktuellen Version wird der Filter in der Zeile nicht korrekt als Array übergeben:
https://github.com/markocupic/calendar-event-booking-bundle/blob/1b7d2723f7b5366db599d3d17fa6546157a2cf05/src/Contao/Dca/TlCalendarEventsMember.php#L47

Ich denke die Zeile sollte
```php
$opt['arrFilter'] = ['pid=?', Input::get('id')];
```
lauten. Nach der Änderung funktioniert der Export wieder wie gewohnt.

**Comment by markocupic** [comment]
Fixed in 0f438f0ae0237a298227b9e60b9abf2c8703efdf
