### ISSUE TITLE
Deep Link Export Funktion funktioniert nicht & http link

### ISSUE THREAD

**Issue by Don-Ron** [markocupic/calendar-event-booking-bundle#22]
Wenn ich versuche den Link für die Exportfunktion zu betätigen werde ich umgeleitet und erhalte keine File mit den Exportdaten.
Zudem ist der Link im Backend als http definiert, was auf einer mit ssl verschlüsselten Seite zuerst einen redirect zu https provoziert.

![exportcsv](https://user-images.githubusercontent.com/22054372/94027755-7ad96280-fdbb-11ea-83b1-51b6af3dd6d0.png)

Request:
![export2](https://user-images.githubusercontent.com/22054372/94028116-e02d5380-fdbb-11ea-878a-f545f3171c5f.png)

**Comment by markocupic** [comment]
Welche Version von markocupic/'export_table hast du installiert?

**Comment by Don-Ron** [comment]
Hi Marko
Ich habe momentan V 3.3.6 in Betrieb.
Eventuell hätte ich die releases besser nachverfolgen sollen ;)

**Comment by markocupic** [comment]
Das heisst, Problem gelöst?

**Comment by Don-Ron** [comment]
Ich schaue es gleich an und werde es, falls gelöst gleich schliessen.
Vielen Dank für die schnelle Reaktion!

**Comment by Don-Ron** [comment]
Hi Marko :)
Funktioniert einwandfrei!
Vielen Dank nochmals und entschuldige die Umstände ;)
