### ISSUE TITLE
Delete participant after 4 weeks (Corona regulations)

### ISSUE THREAD

**Issue by Ernestopheles** [markocupic/calendar-event-booking-bundle#23]
Corona regulations demand to keep the data of participants for 4 weeks and delete them afterwards.

maybe s.o. could add this feature?

**Comment by markocupic** [comment]
Hallo
Du kannst mich via E-Mail kontaktieren, dann setze ich das im Rahmen eines Kleinauftrags um. Adresse findest du im Header jeder Kopfzeile.
Oder du programmierst das selber und machst danach einen Pull Request. 
Liebe Grüße 
Marko
