### ISSUE TITLE
Migrations nicht möglich

### ISSUE THREAD

**Issue by andreheeke** [markocupic/calendar-event-booking-bundle#24]
**Betroffene Versionen**
4.0.x

**Beschreibung**
Bei Installation des Bundles in Version 4 (alle Bugfix-Versionen) können die Migrations anschließend nicht ausgeführt werden.

```
ERROR [console] Error thrown while running command "contao:migrate". Message: "Call to a member function get() on null" ["exception" => Error { …},"command" => "contao:migrate","message" => "Call to a member function get() on null"]

In Database.php line 91:
Call to a member function get() on null
```

**Comment by markocupic** [comment]
fixed in version 4.0.8 189fdfb388d8e4d532e30516ad7820147bb5719b

**Comment by markocupic** [comment]
Removed forgotten var_dump expression ;-) fixed in version 4.0.9 82efce64bf590ed6b606e45d4a9647b20729a035
