### ISSUE TITLE
Maximale Teilnehmerzahl

### ISSUE THREAD

**Issue by webfarben** [markocupic/calendar-event-booking-bundle#26]
Servus Mark,

wenn ich eine Buchung mit Begleiter auslöse, wird nur ein Platz von der Maximalanzahl der Plätze abgezogen. Biete ich also 5 Plätze an und erlaube maximal 5 Begleiter pro Buchung, können 5 x 5 Plätze gebucht werden.

beste Grüße Sebastian

**Comment by markocupic** [comment]
Hallo Sebastian
Ich habe die Extension damals für einen Kunden geschrieben, der das explizit so wollte. 
Du kannst mich per E-Mail kontaktieren, dann entwickle ich die Erweiterung im Rahmen eines Auftrags in die Richtung, dass Plätze von der max. Teilnehmerzahl abgezogen werden, wenn eine entsprechende Option beim Event gesetzt wird. 

Mail-Adresse findest du im Head einer jeden Datei im Code.

Lg Marko
