### ISSUE TITLE
deserialze select fields

### ISSUE THREAD

**Issue by agenturfipps** [markocupic/calendar-event-booking-bundle#27]
We added a select field in the registration form.  
The notification exchanges the field value with an serialized array.

This must be de-/unserialized like the form notification.

I think it is in line 77 of NotfificationHelper

Thanks in advance.

**Comment by markocupic** [comment]
How do you access array values via tokens in a notification center message?

**Comment by agenturfipps** [comment]
##member_field##

Example:  
Here is a snipet of the form:  
![image](https://user-images.githubusercontent.com/43065125/115409363-f8e6d600-a1f1-11eb-8431-6d24ec6d4684.png)


and here of the notification:  
![image](https://user-images.githubusercontent.com/43065125/115408728-67776400-a1f1-11eb-8919-bbe959a55d6c.png)

the result is, that the serialized array will be mailed.  
![image](https://user-images.githubusercontent.com/43065125/115409032-ac02ff80-a1f1-11eb-8fbf-22772127bde5.png)

Better, only the values will be mailed, comma separated.

**Comment by markocupic** [comment]
Fixed in d9444ffa624d740c6bb8dc6f36384120aa15660a

**Comment by markocupic** [comment]
Test version 4.0.12 please. Array values should be sent as a comma separated string now.
