### ISSUE TITLE
no container set

### ISSUE THREAD

**Issue by ch-web-design** [markocupic/calendar-event-booking-bundle#28]
Hallo, bin gerade etwas ratlos. Habe das Buchungsformular via Modul eingebunden und bekomme beim Aufrufen der Seite sowohl im Backend als auch Frontend folgenden Fehler:

"contao.fragment._contao.frontend_module.calendar_event_booking_event_booking_module" has no container set, did you forget to define it as a service subscriber?

**Comment by markocupic** [comment]
contao Version?

**Comment by ch-web-design** [comment]
Ja, Sorry. 4.11.2

**Comment by markocupic** [comment]
Hab gerade keine 4.11. zum Testen. Auf 4.10 weiss ich, dass die Extension läuft. --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 27.04.21, 20:05 schrieb ch-web-design ***@***.***>:

   
  Ja, Sorry. 4.11.2

**Comment by ch-web-design** [comment]
ok ich probiere es mal mit nem downgrade auf 4.10.

**Comment by markocupic** [comment]
Ja, teste mal. Ich schau dann mal, wenn ich Zeit und Musse habe. :-)--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 27.04.21, 20:13 schrieb ch-web-design ***@***.***>:

   
  ok ich probiere es mal mit nem downgrade auf 4.10.

**Comment by ch-web-design** [comment]
Also auf Contao 4.10 läuft alles fehlerfrei :-)

—
Mit freundlichen Grüßen,
Christina Glatz
ch-web.design <https://ch-web.design/>

T: 0800 000 8171
T: 036694 3999 99
M: ***@***.***
www.ch-web.design
Impressum <https://ch-web.design/impressum> | Datenschutz <https://ch-web.design/datenschutz>














Pflichtinformationen gemäß Artikel 13 DSGVO Im Falle des Erstkontakts sind wir gemäß Art. 12, 13 DSGVO verpflichtet, Ihnen folgende datenschutzrechtliche Pflichtinformationen zur Verfügung zu stellen: Wenn Sie uns per E-Mail kontaktieren, verarbeiten wir Ihre personenbezogenen Daten nur, soweit an der Verarbeitung ein berechtigtes Interesse besteht (Art. 6 Abs. 1 lit. f DSGVO), Sie in die Datenverarbeitung eingewilligt haben (Art. 6 Abs. 1 lit. a DSGVO), die Verarbeitung für die Anbahnung, Begründung, inhaltliche Ausgestaltung oder Änderung eines Rechtsverhältnisses zwischen Ihnen und uns erforderlich sind (Art. 6 Abs. 1 lit. b DSGVO) oder eine sonstige Rechtsnorm die Verarbeitung gestattet. Ihre personenbezogenen Daten verbleiben bei uns, bis Sie uns zur Löschung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck für die Datenspeicherung entfällt (z.B. nach abgeschlossener Bearbeitung Ihres Anliegens). Zwingende gesetzliche Bestimmungen – insbesondere steuer- und handelsrechtliche Aufbewahrungsfristen – bleiben unberührt. Sie haben jederzeit das Recht, unentgeltlich Auskunft über Herkunft, Empfänger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Ihnen steht außerdem ein Recht auf Widerspruch, auf Datenübertragbarkeit und ein Beschwerderecht bei der zuständigen Aufsichtsbehörde zu. Ferner können Sie die Berichtigung, die Löschung und unter bestimmten Umständen die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten verlangen. Details entnehmen Sie unserer Datenschutzerklärung <https://ch-web.design/datenschutz>

**Comment by markocupic** [comment]
Hallo Christina
Habe die Erweiterung schnell unter 4.11 durchgetestet. Konnte deinen Fehler nicht reproduzieren.
Liebe Grüsse
Marko
