### ISSUE TITLE
Event in Bestätigungs Email

### ISSUE THREAD

**Issue by Sizoberz** [markocupic/calendar-event-booking-bundle#3]
In der Bestätigunsmail an den Veranstalter, wessen Email man im Forumlar angibt werden nur die Personendaten des Formulars angegeben - nicht aber zu welchem Event die Anmeldung durchgeführt wurde.
D.h. sobald ich zwei Events mit Anmeldungen habe muss ich im Backend schauen für welches Event die Anmeldung war. Was ein Admin oder jemand mit Zugang zum Backend kann, aber ich habe auch den Fall das Veranstaltungen für Frontend user angelegt sind, die nur die Email Benachrichtigung bekommen und die wissen dann nicht für welches Event die Anmeldung war.
Gibt es hier eine Möglichkeit den Event Titel und evtl. das Dateum des Events mit in die Email aufzunehmen?

**Comment by markocupic** [comment]
https://github.com/markocupic/calendar-event-booking-bundle/blob/master/src/Resources/contao/classes/ValidateForms.php#L256-L270

Hier siehst du welche simple tokens ersetzt werden. Der eventname sollte dabei sein, wenn ich mich nicht täusche. Oder nicht?

**Comment by Sizoberz** [comment]
Muss ich die gewünschten Angaben aus dem Event als unsichtbare Felder in das Formular einbauen?

**Comment by Sizoberz** [comment]
In der Mail an den der sich anmeldet funktioniert die übergabe wenn ich ##eventname## in die Mail der Buchungsoptionen des Events eintrage. Ich hätte aber gern den Eventtitel auch in der Mail die an den Admin bzw. wen ich eben im Formular als Empfänger Adresse hinterlege. Ist das möglich?

**Comment by Sizoberz** [comment]
Nein, wie gesagt bin kein Entwickler, ich war schon froh das ich es geschafft habe im Event bei Location noch die Straße, PLZ und Ort anzeigen zu lassen und das CSS des Themes etwas anzupassen :-)
Aber wie man etwas neues einzuprogrammiert weiß ich nicht.

**Comment by markocupic** [comment]
@Sizoberz 
Ab Version 2.0 ist es beim Absenden des Formulars möglich mit dem Notification Center mehrere E-Mails auch an den Event Organisator zu versenden. (Siehe README)
