### ISSUE TITLE
Unsubscribing from an event does not affect leads entries

### ISSUE THREAD

**Issue by JensB74** [markocupic/calendar-event-booking-bundle#33]
I don't know if I'm right here, if it's a leads issue or a calendar event book issue, but if a user unsubscribe from an event, the entry on the leads list will not be deleted.

Please don't hit me, if this is not the problem of your extension ;)

I use the latest Contao Version and the latest extension versions.

---

Nochmal auf deutsch, weil ich mir nicht sicher bin, ob man mein englisch versteht ;)
Wenn ein Benutzer sich von einem Event (z.B. per Abmeldelink in der Mail) abmeldet, dann wird er zwar beim Event gelöscht, nicht aber bei Leads in der Liste. Da ich aber Leads einsetze (bzw. ein Kunde von mir) um eine Excelliste daraus zu erstellen, stimmen die Daten dann nicht mehr überein.

Bitte nicht hauen, falls dass nicht das Problem von dieser Erweiterung ist ;)

Ich setze sowohl die letzte Contao, als auch die letzten Modulversionen ein.

**Comment by markocupic** [comment]
Hi Jens

Grundsätzlich hat calendar-event-booking-bundle keinen Einfluss auf Leads Tabellen. Ich könnte dir einen Event Subscriber programmieren, der dann in Aktion tritt, wenn sich jemand vom Event abmeldet. Er würde dann in der entsprechenden Leads Tabelle die nötigen Einträge mitlöschen.

Müsste das aber vorher genau abklären und wissen, wie die Buchung in Leads abgelegt wurde. Excel-Liste kann calendar-event-booking-bundle übrigens auch. 

Kontaktiere mich per E-Mail, wenn du daran interessiert bist (Adresse findest du in der composer.json).

Liebe Grüsse

Marko

**Comment by JensB74** [comment]
Hallo Marko,

vielen Dank für die superschnelle Antwort und dass Du mir da helfen magst! Komme ich bei Bedarf gerne drauf zurück.

Ich schaue mir jedoch erstmal noch die Excelfunktion von calendar-event-booking-bundle an, ich glaube ich bin nur auf Leads gegangen, weil ich dort alle/weiteren Formularfelder exportieren konnte, ohne in der app/Resources/contao/dca/tl_calendar_events_member.php "rumpfuschen" zu müssen (neue Felder anlegen, da es auch nicht nur EIN Formular werden  und es unterschiedliche Felder geben soll) ;) Aber ich finde Leads etwas überladen ... und wenn ich darauf verzichten könnte, wäre es super ;)

Es gibt ja von Contao auch die Möglichkeit "Eingaben speichern" anzuklicken bei Formularen, um die Daten in der Datenbank zu speichern, kann es sein, dass das ignoriert wird, wenn ich calendar-event-booking-bundle aktiviere? Ich habe es jedenfalls nicht hinbekommen, dass die Daten in einer neuen Tabelle gespeichert werden, habe alle Felder so angelegt wie im Formular vorhanden ... oder soll ich hierfür ein neues Issue aufmachen?

Liebe Grüße und danke nochmals!
Jens

**Comment by markocupic** [comment]
Eigentlich werden alle Felder aus dem Buchungsformular (auch zusätlich angelegte) in tl_calendar_events_member abgelegt, **sofern du dafür via dca ein Feld angelegt hast.**

Siehe hier:
https://github.com/markocupic/calendar-event-booking-bundle/blob/3d5dc316f101a16f1529a9f33e1aceb718594e2f/src/Listener/ContaoHooks/ProcessFormData.php#L85

**Comment by JensB74** [comment]
Ich werd's mir heute Abend mal anschauen und mich dann hier wieder melden. Danke!

**Comment by markocupic** [comment]
Hier ein Beispiel für zwei custom Felder: 
https://gist.github.com/markocupic/41496afeef407c975fa7f88fcb8ccd00
