### ISSUE TITLE
Error for date and datim in List-Template (Startzeit und Endzeit) - in Contao 4.9

### ISSUE THREAD

**Issue by MacKP** [markocupic/calendar-event-booking-bundle#37]
Ich teste gerade dein Modul um zu schauen ob wir das für einen Kunden einsetzen können. Dabei ist mir aufgefallen, dass ich bei vier Ausgben diesen Fehler bekomme:
`
Return value of Markocupic\CalendarEventBookingBundle\Helper\AddTemplateData::Markocupic\CalendarEventBookingBundle\Helper\{closure}() must be of the type int, string returned
`
Es betrifft diese Felder:

- $this->bookingStartDate
- $this->bookingStartDatim
- $this->bookingEndDate
- $this->bookingEndDatim

Ist jetzt nicht so dramatisch, da man das ganze ja auch mit dem timestamp selber lösen kann. Aber fällt eventuell anderen auf die Füße ;-)

Viele Grüße

**Comment by markocupic** [comment]
@MacKP Thank you!

**Comment by MacKP** [comment]
Funktioniert wunderbar. Danke für die schnelle Umsetzung ;-)
