### ISSUE TITLE
one </div> to much

### ISSUE THREAD

**Issue by tobisnet** [markocupic/calendar-event-booking-bundle#38]
Just a hint because I came across this today:

In mod_calendar_event_booking_unsubscribe_from_event_module.html5 is one closing </div> to much.

**Comment by markocupic** [comment]
@tobisnet Could you confirm the bugfix in 3b30d29dfec4ac9e6ec9afa385efa4ce233badc2 please?

**Comment by tobisnet** [comment]
@markocupic just tried it out and it works well. Thx again!
