### ISSUE TITLE
Formular vom Benachrichtigungstyp 'Event-Buchungsbestätigung' kann nicht im Formular als Benachrichtigung ausgewählt werden

### ISSUE THREAD

**Issue by MacKP** [markocupic/calendar-event-booking-bundle#40]
Leider kann ich das Formular nicht mit der Benachrichtigung verknüpfen. Wenn ich als Benachrichtigungstyp 'Formularübertragung' auswähle, kann ich das zwar machen, dann funktionieren die ganzen simple-Tokens vom Event allerdings nicht, da.
Aktuell kann ich das so leider nicht nuzten und weiß auch nicht wirklich wo das Problem zu beheben wäre.

PS: ich hab noch nicht geschaut ob das bei der Benachrichtigungstyp 'Eventstornierung' auch der Fall ist.

Viele Grüße

**Comment by MacKP** [comment]
Oh.. schon gut. Die Verknüpfung erfolgt ja beim Event selber. Das hatte ich übersehen. Danke!

**Comment by rustykowski** [comment]
Hatte eben die gleiche Frage. Die Auswahl der Benachrichtigung beim Formular selbst hätte ich als Neu-User auch erwartet. Die Auswahl der Benachrichtigung beim Event selbst ist fehleranfällig, da sie vergessen werden könnte. Allenfalls wäre dort ein Überschreiben der Default-Benachrichtigung zu überlegen.
