### ISSUE TITLE
AutogenerateBookingForm not compatible with PHP 8

### ISSUE THREAD

**Issue by rabauss** [markocupic/calendar-event-booking-bundle#41]
Unfortunately the migration AutogenerateBookingForm is not compatible with PHP 8.
`Argument #2 ($replace) must be of type array|string, null given` in 
https://github.com/markocupic/calendar-event-booking-bundle/blob/7bcd73d403da173f2ee399f16340c074c90ff8d8/src/Migration/AutogenerateBookingForm.php#L129

The error occurs because there has been defined no `default` for `extensions` in `tl_form_field` since Contao 4.9 - see:
https://github.com/contao/contao/blob/4.9/core-bundle/src/Resources/contao/dca/tl_form_field.php#L283

**Comment by markocupic** [comment]
@rabauss Please try https://github.com/markocupic/calendar-event-booking-bundle/tree/5.2.4

**Comment by rabauss** [comment]
@markocupic: looking good to me!
