### ISSUE TITLE
Anrede funktioniert nicht in E-Mail-Ausgabe

### ISSUE THREAD

**Issue by k-webdesign** [markocupic/calendar-event-booking-bundle#42]
Hi, analog zur Doku habe ich die Anrede in der Mail wie folgt umgesetzt:

{if member_gender=='Herr'}
Sehr geehrter Herr ##member_firstname## ##member_lastname##
{elseif member_gender=='Frau'}
Sehr geehrte Frau ##member_firstname## ##member_lastname##
{else}
Hallo ##member_firstname## ##member_lastname##
{endif}
-> Ergebnis: Es springt immer in Else

{if member_gender=='Herr'}
Sehr geehrter Herr ##member_firstname## ##member_lastname##
{elseif member_gender=='Frau'}
Sehr geehrte Frau ##member_firstname## ##member_lastname##
{elseif member_gender=='Divers'}
Hallo ##member_firstname## ##member_lastname##
{endif}

-> Ergebnis: die gesamte Anrede fehlt

Die Felder heißen:
female (Value) / Frau (Bezeichnung)
male (Value) / Herr (Bezeichnung)
divers (Value) / Divers (Bezeichnung)

Und jetzt weiß ich nicht so recht weiter :/

**Comment by markocupic** [comment]
Hallo Kim

~~Ich glaube die Doku ist falsch, ohne es selber getestet zu haben.~~
~~Hast du das auch probiert:~~

~~{if member_gender=='male'}~~

`{if member_gender=='Männlich'}`

wäre richtig.

Mit welcher Version arbeitest du? Unter der [aktuellsten getaggten Version](https://github.com/markocupic/calendar-event-booking-bundle/tree/5.2.5) sollte es funktionieren, denke ich. 
Kann es sein, dass du mit dem [master-branch](https://github.com/markocupic/calendar-event-booking-bundle) arbeitest? Dort kommt es zu diesem Fehler. Bitte beachte, dass es sich hier um einen Entwicklungsbranch handelt, der noch ungetestet ist.

Liebe Grüsse

Marko

**Comment by k-webdesign** [comment]
Hm... woher kommt denn "Männlich"? Ich hab ein Select-Feld angelegt mit Feldnamen "gender", Bezeichnung ist "Anrede" und die Optionen darin sind die, die ich oben geschrieben hab. 

Wenn ich auf "Männlich" und "Weiblich" abfrage, funktioniert es tatsächlich. Doch dann sind die Werte meines Selects ja völlig hinfällig? Wieso das?
