### ISSUE TITLE
v5.2.7, Bug: Bei Eingabe von Maximal-Teilnehmern = 0 ist eine Anmeldung nicht möglich

### ISSUE THREAD

**Issue by mandrael** [markocupic/calendar-event-booking-bundle#44]
Früher galt der Eintrag "0" als unendlich/unbestimmt, also unbeschränkte Teilnehmeranzahl. Jetzt werden seit dem Update alle Anmeldungen blockiert mit der Fehlermeldung:
"**Die Gesamtzahl von 0 Teilnehmern wird überschritten**. Bitte überprüfen Sie die Anzahl der Begleitpersonen."

Ich habe probiert alternativ "-1" einzutragen, aber ohne Erfolg.
Bitte diesen Bug beheben, da die Erweiterung so ihren Dienst für uns eingestellt hat, bis wir manuell alle Kurse auf eine fiktive TN-Zahl ergänzt haben.

**Comment by markocupic** [comment]
Version?

**Comment by mandrael** [comment]
Version 5.2.7

Ich habe in der Datei /src/Listener/ContaoHooks/ValidateNumberOfParticipants.php folgendes ergänzt und es scheint wieder wie vorher zu funktionieren (hatte mich an der früheren v4-Datei "EventRegistration.php“ orientiert)

Ab Zeile 93:
```
        if ($this->eventRegistration->getBookingMax($objEvent) < $countTotal && $this->maxMembers > 0) {
            $errorMsg = $this->translator->trans('MSC.maxMemberLimitExceeded', [$objEvent->maxMembers], 'contao_default');
            $messageAdapter->addInfo($errorMsg);

            return false;
        }

        return true;
    }
```
("&& $this->maxMembers > 0" ergänzt)

Bitte überprüfen, ob das auch logisch richtig ist; es scheint aber wieder wie immer zu funktionieren :)

**Comment by markocupic** [comment]
Wieso `&& $this->maxMembers` und nicht `$objEvent->maxMembers`?

**Comment by mandrael** [comment]
Ja, so stimmt es, danke :-)
Ich habe es gerade geändert auf "&& $objEvent->maxMembers" und getestet, hat funktioniert.
