### ISSUE TITLE
Double-Opt-in

### ISSUE THREAD

**Issue by dive13** [markocupic/calendar-event-booking-bundle#45]
Hi Marco, tolle Erweiterung!

Nur: wie lässt sich damit ein double-opt-in realisieren?
Folgerichtig müsste es dann so sein, dass unbestätigte bookings noch nicht zur Teilnehmerliste gezählt werden, also so lange inaktiv bleiben.

**Comment by markocupic** [comment]
Du könbtest das über Hooks und das Notification Center dazuprogrammieren. Die Extension bietet nur die Basisfunktionalität. 

Grüsse Marko

**Comment by dive13** [comment]
Danke für das rasche Feedback. Ok, ich verstehe – nun, ich selbst bin dazu leider nicht in der Lage. Könnte ich dich bei Bedarf beauftragen?

**Comment by markocupic** [comment]
Ja, klar! Du kannst mich jederzeit damit beauftragen.
Grüsse Marko
