### ISSUE TITLE
CM findet Datenbank-Problem

### ISSUE THREAD

**Issue by webfarben** [markocupic/calendar-event-booking-bundle#46]
Servus,

ab Version 4.0.1 habe ich eine Systemwarnung im CM -> Datenbank-Migrationen Datenbank-Problem gefunden. Gehe ich auf 3.7.2 zurück, ist der Fehler weg aber das Anmeldeformular wird im Frontend nicht mehr angezeigt.
Führe ich das InstallTool aus, gibt es nichts zu aktualisieren.

Contao 4.13.12
Contao Manager 1.6.1

**Comment by markocupic** [comment]
Fixed issue in version 5.2.11
https://github.com/markocupic/calendar-event-booking-bundle/commit/847cf526b7c9180fb2b820cd370fbf7044fd7e6a

**Comment by webfarben** [comment]
Bin jetzt auf 5.2.10 | Datenbankproblem gelöst | alles sauber | ohne Anmeldeformular im Frontend

Fehler bei der Aktualisierung auf 5.2.11

Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Package operations: 0 installs, 1 update, 0 removals
Upgrading markocupic/calendar-event-booking-bundle (5.2.10 => 5.2.11): Extracting archive
Generating optimized autoload files
contao/manager-plugin: Dumping generated plugins file...
contao/manager-plugin: ...done dumping generated plugins file
Class Contao\ManagerPlugin\PluginLoader located in ./vendor/contao/manager-plugin/src/Resources/PluginLoader.php does not comply with psr-4 autoloading standard. Skipping.
114 packages you are using are looking for funding.
Use the composer fund` command to find out more!
@php vendor/bin/contao-setup

Parse error: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /var/www/vhosts/montessori-regensburg.de/ema.montessori-regensburg.de/vendor/markocupic/calendar-event-booking-bundle/src/Contao/Dca/TlCalendarEvents.php on line 79
PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in /var/www/vhosts/montessori-regensburg.de/ema.montessori-regensburg.de/vendor/markocupic/calendar-event-booking-bundle/src/Contao/Dca/TlCalendarEvents.php on line 79
Script @php vendor/bin/contao-setup handling the post-install-cmd event returned with error code 255

**Comment by markocupic** [comment]
Achso, du hast noch php7.4.
Probiere nochmals ein Update zu machen.

**Comment by webfarben** [comment]
Bin jetzt auf 5.2.13 das hat geklappt. Danke
Jetzt muss ich nur noch das Formular ins Frontend bekommen. Das wird mir nach wie vor nicht angezeigt.

**Comment by webfarben** [comment]
Es waren das Template! mod_calendar_event_booking_event_booking_module.html5
Ich habe zum testen eine weitere Installation angelegt. Hier hatte ich keine Probleme. Lief alles glatt.

Nun habe ich die Templates verglichen und fertig.

Ganz herzlichen Dank für Deinen Support
