### ISSUE TITLE
bookingCount geht nicht mehr

### ISSUE THREAD

**Issue by webfarben** [markocupic/calendar-event-booking-bundle#47]
Servus,

ich habe mir in einer früheren Version (ich verwende jetzt 4.0.7) in der EVENTLISTE den bookingCount anzeigen lassen.
Gibt es eine anderer Möglichkeit diese oder eine ähnliche Funktion mit der Eventlist auszugeben?

        `<div class="booking">
            gebucht <?= $this->bookingCount ?> von <?= $this->maxMembers ?>
         </div>`
        
        `<div class="ausgebucht">
        	<?php
			$int1 = $this->bookingCount;
			$int2 = $this->maxMembers;

			if($int1 >= $int2) { 
			echo "ausgebucht";
			}
		?>
         </div>`

**Comment by markocupic** [comment]
Verwendest du Version 5?
Da sollte das doch möglich sein.

**Comment by markocupic** [comment]
Fixed for 6.x branch.
https://github.com/markocupic/calendar-event-booking-bundle/commit/6f7759acfe3d26557c9d7e8a1b57285517ad8db9

**Comment by webfarben** [comment]
> Verwendest du Version 5? Da sollte das doch möglich sein.
Nein. Bin nun aber auf 5.2.10 und es ist wieder da.
Danke
