### ISSUE TITLE
Attribute werden nicht weiter gereicht

### ISSUE THREAD

**Issue by manjarco** [markocupic/calendar-event-booking-bundle#48]
Moin,

kann es sein, dass von dem über das Modul Event-Buchungsformular eingebundenen Formular nicht alle Attribute weitergereicht werden? Aufgefallen ist mir das durch den Einsatz von terminal42/contao-conditionalformfields. Das funktioniert mit data-Attributen wie `data-cff-condition=""`, die dem Fieldset eigentlich mitgegeben werden. Das Event-Buchungsformular will davon aber nichts wissen. 

Auch die Klassen des Formulars werden nicht in `<form>` geschrieben.

Ist das Absicht/komme ich da irgendwie drumherum?

Contao 4.13
Booking 5.2.13

**Comment by markocupic** [comment]
Schwierig...
Die Extension nutzt codefog/contao-haste für das Formular-Handling. Haste verzichtet beim Parsen des Templates auf die Angabe eines id-Attributes. Ebenso wird die "attributes" Eigenschaft nicht befüllt.

Mit einem parseTemplate Hook könntest du das evtl. umsetzen.

**Comment by manjarco** [comment]
Hooks sind leider Neuland für mich. Werde wohl mit JS drumherum basteln, um mein conditional formfield hin zu bekommen.

Danke trotzdem!
