### ISSUE TITLE
Fehler im Frontend

### ISSUE THREAD

**Issue by planepix** [markocupic/calendar-event-booking-bundle#5]
Hallo Marko,

ich wollte mir einmal dieses Bundle ansehen und bekomme nach der Installation und dem Eintrag eines Events folgende Fehlermeldung im Backend:

Warning: Invalid argument supplied for foreach() in /www/htdocs/xxx/var/cache/prod/contao/dca/tl_calendar_events.php on line 28

Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/xxx/var/cache/prod/contao/dca/tl_calendar_events.php:28) in /www/htdocs/xxx/vendor/contao/core-bundle/src/Resources/contao/library/Contao/System.php on line 675

Ich vermute das es an der Verwendung von PHP 7.2.1 liegt, da im der composer.json ^7.0 steht. Richtig?

**Comment by markocupic** [comment]
Ciao Planepix
Kannst du mal den entsprechenden Ausschnitt posten?

> Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/xxx/var/cache/prod/contao/dca/tl_calendar_events.php:28) in /www/htdocs/xxx/vendor/contao/core-bundle/src/Resources/contao/library/Contao/System.php on line 675

 Die DCA's werden ja gecacht. Was bei dir Zeile 28 ist, ist bei mir ziemlich sicher nicht Zeile 28. 

Liebe Grüsse
Marko

**Comment by planepix** [comment]
Hallo Marko,
aber gerne.

Die Zeilen bis Zeile 49 der Datei tl_calendar_events.php aus dem Cache-Verzeichnis:
```

<?php

namespace  {
use \con4gis\MapsBundle\Resources\contao\classes\GeoPicker;
use con4gis\MapsBundle\Resources\contao\classes\Utils;

/**
 * con4gis - the gis-kit
 *
 * @version   php 7
 * @package   con4gis
 * @author    con4gis contributors (see "authors.txt")
 * @license   GNU/LGPL http://opensource.org/licenses/lgpl-3.0.html
 * @copyright Küstenschmiede GmbH Software & Design 2011 - 2017.
 * @link      https://www.kuestenschmiede.de
 */

if (@class_exists("tl_calendar_events")) {

    /**
     * Change palettes
     */
    $disabledObjects = deserialize($GLOBALS['TL_CONFIG']['disabledC4gMapObjects'], true);

    if (!in_array('tl_calendar_events', $disabledObjects)) {

        //Neu
        foreach( $GLOBALS['TL_DCA']['tl_calendar_events']['palettes'] as $name => $palette )
        {
            if ($name == '__selector__')
                continue;

            $GLOBALS['TL_DCA']['tl_calendar_events']['palettes'][$name] = str_replace(
                array(
                    ';{expert_legend'
                ),
                array(
                    ';{c4g_maps_legend},c4g_loc_geox,c4g_loc_geoy,c4g_loc_label,c4g_locstyle;{expert_legend'
                    ),
                $palette
                );
        }

        //Alt
        //foreach ($GLOBALS['TL_DCA']['tl_calendar_events']['palettes'] as $key=>$palette) {
            //if ($key != '__selector__') {
                //$palette = str_replace(';{expert_legend', ';{c4g_maps_legend},c4g_loc_geox,c4g_loc_geoy,c4g_loc_label,c4g_locstyle;{expert_legend', $palette);
            //}
        //}
```

Und schon wird sichtbar, das es das Zusammenspiel mit con4gis_maps ist, richtig?

**Comment by markocupic** [comment]
Hallo Thomas

 

Ja, so wie es scheint, hat das mit meiner Erweiterung nichts zu tun.

Habe mich schon gewundert. In besagter Datei habe ich nirgendwo eine foreach Schleife reinprogrammiert.

 

Ich kann mir vorstellen, dass bei con4gis der Fehler folgendermassen gelagert ist: 

Wenn die con4gis Erweiterung vor Contao geladen wird, ist natürlich   $GLOBALS['TL_DCA']['tl_calendar_events']['palettes']

 

noch nicht definiert. Das heisst, in der Contao Manager Plugin Klasse muss definiert werden, dass zuerst Contao geladen werden muss. 

 

Dies nur so als Vermutung. ;-)

 

Liebe Grüsse

 

Marko


 

--------------------------------------
Marko Cupic
Surenweidstr. 2
CH-6208 Oberkirch

http://4ae-racing-team.ch
http://kletterkader.com

 
 

Gesendet: Montag, 19. Februar 2018 um 16:56 Uhr
Von: "Thomas Weitzel" <notifications@github.com>
An: markocupic/calendar-event-booking-bundle <calendar-event-booking-bundle@noreply.github.com>
Cc: "Marko Cupic" <m.cupic@gmx.ch>, Comment <comment@noreply.github.com>
Betreff: Re: [markocupic/calendar-event-booking-bundle] Fehler im Frontend (#5)


Hallo Marko,
aber gerne.

Die Zeilen bis Zeile 49 der Datei tl_calendar_events.php aus dem Cache-Verzeichnis:


<?php

namespace  {
use \con4gis\MapsBundle\Resources\contao\classes\GeoPicker;
use con4gis\MapsBundle\Resources\contao\classes\Utils;

/**
 * con4gis - the gis-kit
 *
 * @version   php 7
 * @package   con4gis
 * @author    con4gis contributors (see "authors.txt")
 * @license   GNU/LGPL http://opensource.org/licenses/lgpl-3.0.html
 * @copyright Küstenschmiede GmbH Software & Design 2011 - 2017.
 * @link      https://www.kuestenschmiede.de
 */

if (@class_exists("tl_calendar_events")) {

    /**
     * Change palettes
     */
    $disabledObjects = deserialize($GLOBALS['TL_CONFIG']['disabledC4gMapObjects'], true);

    if (!in_array('tl_calendar_events', $disabledObjects)) {

        //Neu
        foreach( $GLOBALS['TL_DCA']['tl_calendar_events']['palettes'] as $name => $palette )
        {
            if ($name == '__selector__')
                continue;

            $GLOBALS['TL_DCA']['tl_calendar_events']['palettes'][$name] = str_replace(
                array(
                    ';{expert_legend'
                ),
                array(
                    ';{c4g_maps_legend},c4g_loc_geox,c4g_loc_geoy,c4g_loc_label,c4g_locstyle;{expert_legend'
                    ),
                $palette
                );
        }

        //Alt
        //foreach ($GLOBALS['TL_DCA']['tl_calendar_events']['palettes'] as $key=>$palette) {
            //if ($key != '__selector__') {
                //$palette = str_replace(';{expert_legend', ';{c4g_maps_legend},c4g_loc_geox,c4g_loc_geoy,c4g_loc_label,c4g_locstyle;{expert_legend', $palette);
            //}
        //}


Und schon wird sichtbar, das es das Zusammenspiel mit con4gis_maps ist, richtig?

**Comment by planepix** [comment]
Danke für deine Rückmeldung Marko. Dann weise ich die Küstenschmiede mal darauf hin.
