### ISSUE TITLE
Argument 1 passed to App\EventListener\DoSomething::__invoke() must be an instance of Haste\Form\Form

### ISSUE THREAD

**Issue by tognit** [markocupic/calendar-event-booking-bundle#50]
Hallo markocupic

Ich möchte gerne denn Hook "calEvtBookingPostBooking" verwenden und erhalte leider nachfolgende Meldung ...

![Unbenannt](https://user-images.githubusercontent.com/1794459/201326001-d9b83271-b6ea-4b96-bd2e-efd1082df49b.png)

[Habe denn Hook gemäss Anleitung eingebunden](https://github.com/markocupic/calendar-event-booking-bundle#mit-hooks-frontend-module-erweiternanpassen)

calendar-event-booking-bundle 6.x
Contao 4.13
php 7.4.32

**Comment by code4nix** [comment]
Hallo Steve
Ja, das ist nicht mehr ganz aktuell.
Siehe https://github.com/markocupic/calendar-event-booking-bundle/blob/7ef3acfedae0fca239f7206f3bf904a831572724/src/EventListener/ContaoHooks/PostBooking/ContaoLog.php#L15

Anm. Version 6.x ist noch nicht stable.
