### ISSUE TITLE
No booking Token if user is generated in the backend

### ISSUE THREAD

**Issue by MacKP** [markocupic/calendar-event-booking-bundle#52]
The big issue here is: If you delete the token from the url to reject the event you will see the first uyer without any token here... In that case you can delete every User and see every Name on the Page.

Kind regards

**Comment by MacKP** [comment]
In that case there should be a Token generated in the Backend.

**Comment by markocupic** [comment]
@MacKP This is a serious issue, Thank you for reporting it. Please check the correspondig [fix](https://github.com/markocupic/calendar-event-booking-bundle/commit/299436bb35f589b5e2fd0952aeaa2145ea62d3b9) and update the extension to version 5.3.0 and run contao migrate.
