### ISSUE TITLE
Template variables not working due to a typo in AddTemplateData

### ISSUE THREAD

**Issue by SimonSpi** [markocupic/calendar-event-booking-bundle#55]
In the constructor of calendar-event-booking-bundle/src/Helper/AddTemplateData.php of version 5.4.2 there is a typo which prevents the template variables from working properly. 

Typo:
"$evenRegistration" should be "$eventRegistration" 

see https://github.com/markocupic/calendar-event-booking-bundle/blob/9d624cb1427e4415ec6729af860b23ac09ae224a/src/Helper/AddTemplateData.php#L24

Unfortunately I'm still required to use this version because I am so far unable to upgrade to Contao 5. It would thus be great if it could be corrected. Many thanks for all the work that has gone in this very helpful extension

**Comment by markocupic** [comment]
@SimonSpi Thank you!
