### ISSUE TITLE
module-templates in 6.x

### ISSUE THREAD

**Issue by rustykowski** [markocupic/calendar-event-booking-bundle#56]
ich habe eben versuchsweise von Version 5.4 auf 6.x-dev aktualisiert.
Daraufhin konnte ich keine Templates mehr modifizieren. Sie erscheinen nicht mehr in der Original-Template-Auswahl.
Contao-Version ist 4.13.23.

**Comment by markocupic** [comment]
Kann ich nicht bestätigen. Wo hast du das angepasste Template abgespeichert? Und welchen Dateinamen trägt es?

**Comment by rustykowski** [comment]
Ich hatte ein Template mod_calendar_event_booking_event_booking_module.html5 erstellt. Es wird aber ignoriert, egal ob ich es direkt in templates speichere oder in einem Unterverzeichnis.
Wenn ich versuche, ein neues Template über Templates > Neues Template zu erstellen, werden mir keine Templates zur Auswahl angeboten, die aus dem calendar-event-booking-bundle stammen.

**Comment by markocupic** [comment]
Wieso html5 und nicht twig?

**Comment by rustykowski** [comment]
in das Twig-Thema habe ich mich offen gestanden noch nicht eingearbeitet. Bin ja auch noch auf Contao 4.

**Comment by markocupic** [comment]
Version 6, wenn einmal stable, wird schwer auf Contao 5 abzielen und an TWIG führt früher oder später ohnehin keine Weg vorbei.

**Comment by tognit** [comment]
**Ich kann das bestätigen!** Unter Contao 4.13.25 kann man z.B. das Template "mod_calendar_event_booking_event_booking_module" unter Templates nicht auswählen und modifizieren. Auch wenn man dieses manuel anlegt und im Frontendmodul auswählt, werden die Templatedaten nicht ausgegeben.

**Comment by markocupic** [comment]
Wie heisst dein angepasstes Template mit Dateiendung?

**Comment by tognit** [comment]
mod_calendar_event_booking_event_booking_module.html.twig

![templates](https://github.com/markocupic/calendar-event-booking-bundle/assets/1794459/18d4e758-468a-45e1-be44-2f0296800d81)

Aber auch unter "Templates" kann man keine Templates der Erweiterung auswählen.
