### ISSUE TITLE
Contao 5.x

### ISSUE THREAD

**Issue by sdahlmann** [markocupic/calendar-event-booking-bundle#58]
Frage: Ist es geplant, die Contao Erweiterung "markocupic/calendar-event-booking-bundle" an Contao 5.x anzupassen?

**Comment by markocupic** [comment]
Auf Anfrage im Rahmen eines Auftrags "ja". 

Da im Moment das `[Notification Center]("[markocupic/composer-file-copier-plugin](https://github.com/terminal42/contao-notification_center/tree/1.7.2#which-version-should-i-choose)")` noch nicht Kompatibel Contao 5.x ist, muss ohnehin abgewartet werden.

**Comment by derkosmonaut** [comment]
Hi @markocupic , wir würden die Erweiterung evtl. bei einem kleinen Projekt demnächst einsetzen. Können wir dich bei der Anpassung auf Contao 5 finanziell unterstützen?

**Comment by markocupic** [comment]
@derkosmonaut 
Ciao, das wäre natürlich mega nett. 
Die Erweiterung sollte unter C5 laufen, denke ich. 
Ich bin aktuell noch an einem Nachfolger dran, wo auch payment Lösungen möglich sein sollten. Ist aber noch nicht spruchreif. 
Wenn ihr mich supporten möchtet, darfst du gerne Kontakt aufnehmen per Email. 
Danke.
https://github.com/markocupic/calendar-event-booking-bundle/blob/9ae85b05b991fa9ef14f83dd79f14f1c0530698f/src/ContaoManager/Plugin.php#L8
