### ISSUE TITLE
Formular mit mp_forms, conditionalformfields einbinden

### ISSUE THREAD

**Issue by mj1985** [markocupic/calendar-event-booking-bundle#59]
Moin,
wir nutzen aktuell für das Anmeldeformular die Erweiterungen 
```
        "terminal42/contao-ajaxform": "^1.1",
        "terminal42/contao-mp_forms": "^5.0",
        "terminal42/contao-conditionalformfields": "^3.0",
```
Wenn ich das Formular als Anmeldeformular über das Modul "Event-Buchungsformular" einbinde, dann werden diese Erweiterungen ignoriert.
Liegt hier ein Bug vor oder ist das eher ein kostenpflichtiger Feature-Wunsch? Bei letzterem würden wir dies natürlich unterstützen.
Genutzt wird `"markocupic/calendar-event-booking-bundle": "^5.4"` (5.4.4) (getestet `"markocupic/calendar-event-booking-bundle": "6.0.0-RC3"`) unter Contao 4.13.28 und PHP 8.1

**Comment by markocupic** [comment]
Nein das ist kein Bug. Damals beim Erstellen der Anwendung für einen Kunden war das einfach nicht die Anforderung. 
Ich könnte die Erweiterung schon dahin entwickeln, dass die Kompatibilität mit den drei erwähnten Extensions kompatibel wäre. 
Dies jedoch nicht **ohne** einen **BC break** auszulösen. 

Bitte nimm doch per [E-Mail Kontakt](https://github.com/markocupic/calendar-event-booking-bundle/blob/0c8ae671bbaf228650901036810188f8ae744a7a/contao/dca/tl_calendar.php#L8) mit mir auf, wenn du weitere Informationen dazu wünschst. 
Grüsse Marko

**Comment by markocupic** [comment]
@mj1985 
Habe vorher einmal getestet, ob sich die beiden terminal42 Extensions unten mal **ganz unabhängig** von `markocupic/calendar-event-booking-bundle` gegenseitig vertragen. 
```
"terminal42/contao-ajaxform": "^1.1",
"terminal42/contao-mp_forms": "^5.0",
```
Ich konnte es unter contao 4.13 nicht zum fehlerfreien Laufen bringen. Geht das bei dir? 

Unter Contao 5 gehört die Ajax Extension zum Core. Auch hier konnte ich kein funktionierendes mehreseitiges Formular mit Ajax erstellen. Er kommt nicht über die 2. Seite hinaus und fängt immer wieder bei der ersten Seite an.

**Comment by mj1985** [comment]
@markocupic Ja, das funktioniert bei mir. Die einzelnen Schritte laden zwar nicht per Ajax, aber die Bestätungsmeldung kommt per Ajax rein und das Formular wird abgeschickt.
Am wichtigsten wäre hier allerdings die Einbindung von mp_forms und conditionalformfields, auf Ajax könnten wir an der Stelle verzichten.
Ich melde mich Montag per Mail

**Comment by markocupic** [comment]
Kannst mir dann am besten mal einen Screenshot senden, wie das Formular aufgebaut ist.

**Comment by mj1985** [comment]
Hier, dieses habe ich gerade getestet (mp_forms & Ajax): 
![image](https://github.com/markocupic/calendar-event-booking-bundle/assets/5830093/5b57b536-6dfd-4d03-8862-b06b79dd4b79)

Wir haben dann noch ein Anmeldeformular mit conditionalformfields-Optionen.
