### ISSUE TITLE
addBookingForm Ajax fügt ganze Seite hinzu

### ISSUE THREAD

**Issue by Olli** [markocupic/calendar-event-booking-bundle#6]
Hi,
es wird beim Hakensetzen von "Buchungsoption öffnen" anstatt des des Partials für die Buchungsoption das ganze Event-Formular eingefügt. Beispiel → https://imgur.com/oJMSjbZ
Das passiert wie im Titel geschrieben, nur wenn man die Option setzt. Wenn man den Event abspeichert wird der Formularteil eingefügt.
Ich benutze Contao 4.5.2  und PHP 7.2 .

**Comment by markocupic** [comment]
Hallo Olli
Den Fehler hatte ich in einer älteren Version auch mal. Sollte aber eigentlich behoben sein. Ich kann das jedenfalls nicht reproduzieren, 

Übrigens habe ich soeben Version 2.0 veröffentlicht. Die Benachrichtigung wird hier über terminal42/notification_center geregelt.

Liebe Grüsse

Marko

**Comment by Olli** [comment]
Version 2 ist cool - das mit dem Notification Center ist eine große Verbesserung. Trotzdem der Bug bleibt leider. Ich habe jetzt von 4.5.2 auf 4.5.6 geupdatet und es hat leider keine Änderung gebracht.
War brauchst du um das Problem nachzuvollziehen?

**Comment by markocupic** [comment]
@Olli 
Lade dir mal Version 2.0.1. Ich habe da noch etwas Kleines entdeckt (Semikolon zu viel), was vielleicht den Ausschlag gegeben hat. Ansonsten weiss ich auch nicht, was das Problem sein könnte.

Wie gesagt, das Problem zeigt sich bei meinen Installationen nicht,

Lg M

**Comment by Olli** [comment]
Jupp das wars! Thx :)
