### ISSUE TITLE
CSV-Export mit kryptischen Sonderzeichen

### ISSUE THREAD

**Issue by pepesale** [markocupic/calendar-event-booking-bundle#61]
Nach einem Update bekomme ich in den CSV-Exports der Teilnehmerlisten eines Events anstatt der Umlaute kryptische Zeichen.
Aktuell:
Contao 4.13.24 
PHP 8.1
calendar-event-booking-bundle  5.3.3

Unter Contao 4.9 mit calendar-event-booking-bundle 4.x hatte mein Kunde die Probleme noch nicht.

Gibt es da eine Einstellungsmöglichkeit, die ich nicht kenne?
Das nachträgliche Bearbeiten/Importieren zum Umgehen des Problems in Excel kenne ich zwar, das möchte der Kunde aber nicht.

**Comment by rustykowski** [comment]
Dein Editor bzw. deine Tabellenkalulation sollte dich bei Öffnen einer CSV-Datei nach dem verwendeten Zeichensatz fragen. Die Sonderzeichen werden vermutlich korrekt angezeigt, wenn du Unicode (UTF-8) angibst. Der Editor kann von sich aus nicht wissen, um welchen Zeichensatz es sich handelt.

**Comment by markocupic** [comment]
> Nach einem Update bekomme ich in den CSV-Exports der Teilnehmerlisten eines Events anstatt der Umlaute kryptische Zeichen. Aktuell: Contao 4.13.24 PHP 8.1 calendar-event-booking-bundle 5.3.3
> 
> Unter Contao 4.9 mit calendar-event-booking-bundle 4.x hatte mein Kunde die Probleme noch nicht.
> 
> Gibt es da eine Einstellungsmöglichkeit, die ich nicht kenne? Das nachträgliche Bearbeiten/Importieren zum Umgehen des Problems in Excel kenne ich zwar, das möchte der Kunde aber nicht.

@pepesale Falls das im Rahmen eines Miniauftrags umgesetzt werden soll, kannst du mich gerne kontaktieren per [E-Mail].(https://github.com/markocupic/calendar-event-booking-bundle/blob/4350cb28a98ce790b413197d4b5a89ae80e59800/src/EventBooking/Booking/BookingState.php#L8)
