### ISSUE TITLE
Contao 5 DCA Anpassungen

### ISSUE THREAD

**Issue by derkosmonaut** [markocupic/calendar-event-booking-bundle#65]
Das Hinzufügen von Feldern via DCA klappt nicht in Contao 5 – ansonsten läuft die Erweiterung reibungslos. Hast du dafür einen Workarround?

Ach ja: Das Frontend Modul "Event-Buchungsformular" erstellen und in den Modul-Einstellungen das bei Punkt 6 erstellte Formular auswählen und die Weiterleitungsseite angeben. – Die Weiterleitungsseite kann man unter Contao 5 nicht auswählen.

**Comment by markocupic** [comment]
Welche Version nutzt du denn?

**Comment by derkosmonaut** [comment]
Contao 5.3.11 / Modul Version 5.5.1

**Comment by markocupic** [comment]
Wo hast du die neuen Felder angelegt?

**Comment by derkosmonaut** [comment]
Anhand deines Beispiels unter: contao/dca/tl_cebb_registration.php

**Comment by markocupic** [comment]
Du hast die Readme von Der noch nicht stabil laufenden Version 6.x gelesen. 

Hier ist das Manual von 5.x:

https://github.com/markocupic/calendar-event-booking-bundle/tree/5.x

Die Tabelle heisst tl_calendar_events_member

**Comment by derkosmonaut** [comment]
Asche über mein Haupt! Danke!

**Comment by markocupic** [comment]
Gerne :-)--Gesendet mit der GMX Mail AppAm 12.07.24, 10:31 schrieb derkosmonaut ***@***.***>:

   
  Asche über mein Haupt! Danke!
