### ISSUE TITLE
Multiple Timeslots

### ISSUE THREAD

**Issue by mike-tuxedo** [markocupic/calendar-event-booking-bundle#66]
Hallo,
ich würde das Tool für Terminbuchungen verwenden, brauche da aber pro Tag X Timeslots. Also zB von 10:00-10:30, von 11:00-11:30 usw. In dem Fall muss ich für jeden Timeslot ein eigenes Event erstellen, ein Setting für diverse Timeslots oder ähnliches gibt es da nicht richtig?

PS: Das mit dem "Event wiederholen" wäre fasst prädistiniert dafür, das geht aber nur minimal Tageweise.

Contao: 5.3.12
Plugin: 5.5.1

**Comment by markocupic** [comment]
@mike-tuxedo Mir ist nicht ganz klar, was du meinst. Benötigst du für jeden Tag ein anderes Timeslot-System?

**Comment by mike-tuxedo** [comment]
@markocupic Jaein das ist nicht ganz die Problemstellung. Ich habe zB pro Tag 10 Timeslots zum Anmelden für ein Beratungsgespräch. Wenn ich das für 5 Tage anlegen will, muss ich dafür aktuell 50 eigene Events erstellen, mit dem jeweiligen Timeslot.

Ich kann natürlich ein Eventarchiv mit den 10 Events anlegen und dann dieses Archiv für jeden Tag kopieren und dann einfach das Datum bzw den Tag bei den einzelnen Events ändern. Ich wollte nur hinterfragen, ob es da einen eleganteren Weg mit eurem Plugin gibt, den ich vlt übersehen habe.

**Comment by markocupic** [comment]
Das Plugin ist vom Contao Event Modul unabhängig und es besteht keine Schnittstelle dazu.

**Comment by mike-tuxedo** [comment]
Ok, das verstehe ich jetzt nicht. In der Readme steht ja, dass man es mit Eventliste und Eventreader verwendet. Das Plugin ergänzt ja auch die Felder im Eventdetail wie "maximale Teilnehmer" usw.

Könnte man das Plugin etwa auch mittels Catalogmanager benutzen, wenn man damit zB eine Timeslot Tabelle aufbaut?

**Comment by markocupic** [comment]
AH, sorry: Ich habe falsch gelesen. Weil du von Timeslots gesprochen hast, habe ich gedacht, du meinst diese Extension:
https://github.com/markocupic/resource-booking-bundle

Vielleicht wäre das genau das, was du suchst?

**Comment by mike-tuxedo** [comment]
Vielen Dank, das scheint besser geeignet zu sein. Ich hab es zwar in der Contaoerweiterungen Suche schon gelesen, aber nicht genauer beachtet, da ich dachte es sei nicht passend. Aber eine Resource kann wahrscheinlich genauso ein Besprechnungstermin sind. :+1:

**Comment by markocupic** [comment]
Ja, eine Resource kann alles Mögliche sein. 
Cooles Tool :-)
