### ISSUE TITLE
welche Version zum Testen?

### ISSUE THREAD

**Issue by cmette** [markocupic/calendar-event-booking-bundle#72]
Ich versuche gerade unter C5.3.19 und PHP 8.3.12 das Bundle in der neuesten -dev oder RC zu installieren, aber das will mir nicht so ganz gelingen. Kann jmd. helfen?
Wenn ich also ^6.0 angebe, erhalte ich eine 6.x-dev (ich habe minimum-stability: dev). 
Der CM bietet mir dann eine neuere 6.0-beta2 an. Wenn ich diesen String setze, so erhalte ich eine (aus meiner Sicht unsinnige) Warnung, dass diese neuere beta nur Contao 4.13 unterstützt. Das kann ich mir nicht vorstellen, während die 6.0 ja bereits 5.3.* unterstützt.
![grafik](https://github.com/user-attachments/assets/e466eb81-6cf6-4c14-8df3-61c1376b1a6b)
Dann gibt es laut Tag-List noch eine RC4. Diese kann ich auch nicht installieren. Da erhalte ich ebenfalls die Warnung, dass C4.13 required wird. 
Kann mir jmd. einen Tipp geben?

**Comment by cmette** [comment]
und... gemäß der Anleitung "empfohlener Ablauf" bekomme ich kein Buchungsformular und auch keine Stornierungsseite zu sehen. Ich habe alles zweimal gelöscht und neu Angelegt. Gibts da noch mehr zu beachten?

**Comment by markocupic** [comment]
Nimm die 5.x Version. 6.x ist nicht stable.
