### ISSUE TITLE
ist das Bundle tot?

### ISSUE THREAD

**Issue by cmette** [markocupic/calendar-event-booking-bundle#73]
Hallo Herr Cupic,
ist das Bundle noch in Entwicklung? 
Ich hätte noch weitere Fragen... einiges funktioniert beim Test der 6.0er Version nicht so richtig... aber hier herrscht Funkstille?

**Comment by markocupic** [comment]
Nein, nein, das Bundle ist nicht tot. Und Version 5 ist stable. Bei der Version 6 ist es noch nicht klar, wohin die Reise führen wird.
LG Marko
