### ISSUE TITLE
An- und Abmeldung werden versendet

### ISSUE THREAD

**Issue by katgirl** [markocupic/calendar-event-booking-bundle#74]
Wir haben sowohl die An-, als auch Abmelde-Benachrichtigung unter Benachrichtigungen ausgewählt. Doch es werden immer beide E-Mails bei der Anmeldung versendet.
Bei der eigentlichen Abmeldung kommt dann aber keine Mail mehr.

![image](https://github.com/user-attachments/assets/95619bb8-46aa-4a3a-914a-4822a1191810)
![image](https://github.com/user-attachments/assets/26cce23d-6eae-45ad-8fab-3f6362446fe2)

**Comment by markocupic** [comment]
@katgirl
Lass die Benachrichtigungen auf Formularebene weg. 

Die Stornierungsbenachrichtigungs-Einstellung machst du im Stornierungsmodul selber.
Die Buchungsbenachrichtigung machst du beim Event.

Ich werde heute oder morgen einen Patch committen, sodass auf Formularebene gar keine Benachrichtigungen mehr ausgewählt werden können.

**Comment by katgirl** [comment]
Vielen Dank das hat wunderbar geklappt. Hatte nicht gesehen, das man am Modul auch was auswählen kann.
